### PR TITLE
feat: :sparkles: use template from local

### PR DESCRIPTION
**Pull request by haoyanwang**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [✅] The commit message follows our guidelines: https://github.com/xun082/create-neat/blob/master/CONTRIBUTING.md
- [✅] Tests for the changes have been added (for bug fixes / features)
- [✅] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?
new feature that support dev params to use loca tgz 

```
[ ] Bugfix
[✅] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

## What is the current behavior?

- Closes https://github.com/xun082/create-neat/issues/27
- Related to https://github.com/xun082/create-neat/issues/27

## What is the new behavior?
support dev params to use loca tgz 

## Does this PR introduce a breaking change?

```
[ ] Yes
[✅] No
```

### CODE REVIEW

**Comment by haoyanwang** [comment]
https://github.com/xun082/create-neat/issues/27

**Comment by uaenaTzx** [comment]
首先 pr 提交的说明不用给 ✅，下面这几个提交后可以手动勾选的
-[] The commit message follows our guidelines: https://github.com/xun082/create-neat/blob/master/CONTRIBUTING.md
-[] Tests for the changes have been added (for bug fixes / features)
-[] Docs have been added / updated (for bug fixes / features)

**Review by uaenaTzx — COMMENTED** [review]
逻辑实现没有大问题，一些细节现在也不用去规范，因为考虑到后面重构，会对一些核心逻辑之外的配置做调整。

**Comment by uaenaTzx** [comment]
@xun082 你再过一下看看

**Review by xun082 — APPROVED** [review]

**Comment by haoyanwang** [comment]
> 首先 pr 提交的说明不用给 ✅，下面这几个提交后可以手动勾选的 -[] The commit message follows our guidelines: https://github.com/xun082/create-neat/blob/master/CONTRIBUTING.md -[] Tests for the changes have been added (for bug fixes / features) -[] Docs have been added / updated (for bug fixes / features)

👌

**Pull request merged**
